#!/usr/bin/env bash
# This script manages the my_process by starting, stopping, or restarting it.

file=/var/run/my_process.pid

if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo $! > "$file"
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    pkill -f ./manage_my_process
    rm -f "$file"
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    pkill -f ./manage_my_process
    rm -f "$file"
    ./manage_my_process &
    echo $! > "$file"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
